### ISSUE TITLE
The sfml recipe is not working

### ISSUE THREAD

**Issue by sztomi** [pfultz2/cget-recipes#10]
It is trying to install to a non-user location:

    -- Installing: /Library/Frameworks/FLAC.framework . 
    CMake Error at cmake_install.cmake:55 (file):
      file INSTALL cannot make directory "/Library/Frameworks/FLAC.framework":
      Permission denied

**Comment by pfultz2** [comment]
Hmm, it shouldn't be installing FLAC. It looks like it doesn't find FLAC on mac. I wonder if its because SFML sets `CMAKE_OSX_ARCHITECTURES`.

**Comment by pfultz2** [comment]
So, as a workaround you can set [`CMAKE_FIND_FRAMEWORK`](https://cmake.org/cmake/help/v3.9/variable/CMAKE_FIND_FRAMEWORK.html#variable:CMAKE_FIND_FRAMEWORK) to `LAST` by doing `cget install sfml -DCMAKE_FIND_FRAMEWORK=LAST`. I'll add that setting to the recipe. 

Ultimately, I think `LAST` should be the default. I am not sure why cmake chooses `FIRST` as the default. Maybe a better option would be to set that in the toolchain.

**Comment by pfultz2** [comment]
So this is fixed on master now.
