### ISSUE TITLE
curl on Windows can not find LibreSSL and libssh2

### ISSUE THREAD

**Issue by pbtrung** [pfultz2/cget-recipes#17]
I have tried to install curl on Windows using cget but for some reasons, it can not find LibreSSL and libssh2.
Other dependencies were installed just fine.
Please let me know if you need further information.
Thanks.

**Comment by pfultz2** [comment]
Is this during build? Or during run? Can you provide the output of the error?

**Comment by pbtrung** [comment]
I  was using my own fork of your cget-recipes ([pbtrung/cget-recipes](https://github.com/pbtrung/cget-recipes)). The fork is mostly identical to your repo except that nghttp2 does not depend on boost.  
As far as I remember, there was no error during build. The output of CMake when building curl showed no trace of LibreSSL and libssh2, so HTTPS/FTPS/SSH was not supported. Also, the built binary (curl.exe) does not work at all.
I will post the output here in 1 or 2 days when I have some spare time.

**Comment by pfultz2** [comment]
> As far as I remember, there was no error during build.

Ok, so windows doesn't support rpath, so you need to add the path to the dlls to your system path for it to run. They are usually stored in the `$CGET_PREFIX/bin`. Alternatively, you can build everything static with `cget init --static`.

> The output of CMake when building curl showed no trace of LibreSSL and libssh2, so HTTPS/FTPS/SSH was not supported.

You can do `cget list` to see which packages are installed.

**Comment by pbtrung** [comment]
I have not had time to check again yet.
Thanks for your support.
Close this for now.
