### ISSUE TITLE
BZip download no longer works

### ISSUE THREAD

**Issue by armedturret** [pfultz2/cget-recipes#21]
The link http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz is dead. Please update it to a working download.

**Comment by bukuta** [comment]
I meet the same problem.
I change the content of `./cget/etc/cget/recipes/bzip2/package.txt`  to 
```
https://gitlab.com/bzip/bzip2/-/archive/master/bzip2-master.tar.gz -X build.cmake 
```
and it works for me.

while (https://gitlab.com/bzip/bzip2) says 
>www.bzip.org domain expired sometime late 20180808.

**Comment by armedturret** [comment]
I forked it and replaced with a different download but that one is probably cleaner.

**Comment by pfultz2** [comment]
This has been updated on master.

**Comment by DarkWingMcQuack** [comment]
bzip2 does not seem to work anymore. When i am installing boost i get the following error:
```
Downloading https://gitlab.com/bzip/bzip2/-/archive/d2742e07c4257b51809d25ddaa2c9ee047b7a278/bzip2-d2742e07c4257b51809d25ddaa2c9ee047b7a278.tar.gz
  [----------------------------------------------------------------------]    0%
Unexpected error: <class 'urllib.error.HTTPError'>
HTTP Error 401: Unauthorized
Failed to build package boost
```
